In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_data_updated.csv')
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
2,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
3,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
4,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [3]:
#  Strip whitespace from all string fields
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

C:\Users\HP\AppData\Local\Temp\ipykernel_4668\4005556958.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [4]:
missing_df= df.isnull().reset_index()

In [5]:
#  Fill missing values for key demographic fields
df['Country'] = df['Country'].fillna('Unknown')
df['EdLevel'] = df['EdLevel'].fillna('Unknown')

In [6]:
# Split multi-value Column- 
# Step 5: Explode all multi-value columns
multi_value_cols = [
    'LanguageHaveWorkedWith', 'DatabaseHaveWorkedWith', 'PlatformHaveWorkedWith', 'WebframeHaveWorkedWith',
    'LanguageWantToWorkWith', 'DatabaseWantToWorkWith', 'PlatformWantToWorkWith', 'WebframeWantToWorkWith'
]

for col in multi_value_cols:
    df[col] = df[col].fillna('')
    df[col] = df[col].apply(lambda x: [i.strip() for i in str(x).split(';')] if x else [])

In [9]:
exploded_frames = []

for col in multi_value_cols:
    temp = df[['ResponseId', 'Age', 'Country', 'EdLevel']].copy()
    temp[col] = df[col]
    temp = temp.explode(col)
    temp = temp[temp[col] != '']
    temp.rename(columns={col: 'Value'}, inplace=True)
    temp['Source'] = col
    exploded_frames.append(temp)

# Combine all exploded frames
df_exploded = pd.concat(exploded_frames, ignore_index=True)

In [10]:
df_exploded.to_csv('survey_cleaned.csv.gz', index=False, compression='gzip')

In [11]:
print('Done')

Done